# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android/support -r features/android/helpers -r features/step_definitions -r features/android/pages/

android_login: PLATFORM=android -r features/support -r features/android/support -r features/android/helpers -r features/step_definitions -r features/android/pages/ --tags @add_blog

ios: APP_BUNDLE_PATH=/Users/JustinNguyen/Documents/CruiseControliOS/ios_source/3.3.1/build/Applications/WordPress.app PLATFORM=ios -r features/support -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages

ios_invalid_login: APP_BUNDLE_PATH=/Users/JustinNguyen/Documents/CruiseControliOS/ios_source/3.3.1/build/Applications/WordPress.app PLATFORM=ios -r features/support -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages --tags @invalid_login
